# Generated by Django 3.0 on 2021-04-09 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('porteiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=194, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('numero_casa', models.PositiveIntegerField(verbose_name='Numero da Casa visitada')),
                ('placa_veiculo', models.CharField(blank=True, max_length=7, null=True, verbose_name='Placa do veículo')),
                ('horario_chegada', models.DateTimeField(auto_now_add=True, verbose_name='Horario de Chegada na Portaria')),
                ('horario_saida', models.DateTimeField(blank=True, null=True, verbose_name='Horario de Chegada na Portaria')),
                ('horario_autorizacao', models.DateTimeField(blank=True, null=True, verbose_name='Horario de Autorização de Entrada')),
                ('morador_responsavel', models.CharField(blank=True, max_length=194, verbose_name='Morador responsável pela autorização da entrada')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='porteiros.Porteiro', verbose_name='Porteiro responsavel pelo registro')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'db_table': 'visitantes',
            },
        ),
    ]
