# Generated by Django 3.0 on 2021-04-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitantes',
            name='horario_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horario da Saida'),
        ),
    ]
